title: Andy Wu
logo: assets/img/headshot_circle.png

description: 
  >
  <p align="center">
  <a href="mailto:anwu0203@gmail.com">Email</a> |
  <a href="https://github.com/anwu0203/">GitHub</a> |
  <a href="https://www.linkedin.com/in/andy-wu-b0315b1ba/">LinkedIn</a>

  B.S. - Computer Science University of California, Santa Barbara (_June 2023)

theme: jekyll-theme-minimal
